# Generated by Django 5.2.7 on 2025-10-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naalikeraapp', '0002_authentication_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], default='registration', max_length=20),
        ),
    ]
