# Generated by Django 5.2.7 on 2025-10-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naalikeraapp', '0003_alter_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
